name: Docker Image CI

on:
  push:
    tags: [ "v*" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: repigeons/s3http

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Get tag
      id: get_tag
      run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Login to docker.io
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          ghcr.io/repigeons/s3http:latest
          ghcr.io/repigeons/s3http:${{ steps.get_tag.outputs.TAG }}
          docker.io/repigeons/s3http:latest
          docker.io/repigeons/s3http:${{ steps.get_tag.outputs.TAG }}
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
        push: true
